### ISSUE TITLE
nodenv install 8.11.2 is missing

### ISSUE THREAD

**Issue by gevorggalstyan** [nodenv/nodenv#104]
According to [https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V8.md#8.11.2](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V8.md#8.11.2) `node v8.11.2` has been released on 2018-05-15, but it is missing in the lists.

```
nodenv install -list
# list is missing 8.11.2
```

Trying to simply install it you see the following

```
nodenv install 8.11.2
node-build: definition not found: 8.11.2

See all available versions with `nodenv install --list'.

If the version you need is missing, try upgrading node-build:

  brew update && brew upgrade node-build
```

Doing as suggested I get this response

```
brew update && brew upgrade node-build
Updated 1 tap (homebrew/cask).
No changes to formulae.
Error: node-build 3.0.10 already installed
```

**Comment by novemberborn** [comment]
`node-build` can be found here: https://github.com/nodenv/node-build. It does have the definition, but I don't know how often it updates on Homebrew. I wonder if the update process should be easier.

Personally I use https://github.com/nodenv/node-build-update-defs which pulls down the latest versions directly.

**Comment by gevorggalstyan** [comment]
Thanks for pointing that plugin out. I still find myself a bit off with the fact that all 3 repos are under the same `nodenv` organization, but you need to have some additional plugins to achieve the this you would normally expect. I do agree with you that the most natural direction is to have an easier update process.
