### ISSUE TITLE
Possible to override NPM version separate from the local/global Node?

### ISSUE THREAD

**Issue by hjdarnel** [nodenv/nodenv#105]
Is it possible to select, say, NPM@6.0.0 globally or locally instead of always using the NPM that comes with the Node version selected? I assume I could go in and remove the shim for NPM, but I wanted to see if there was a supported way to do this. I work in repositories that run on specific versions of Node, but my team wants to use NPM6's security features.

I would also be okay with simply using the system NPM in this case (and I could just install NPM versions with brew)

Thanks

**Comment by jasonkarns** [comment]
The npm global install is installed with the node version itself, which means you can create specific "node versions" that have specific desired versions of npm.

Say you have node 8 installed (which ships with npm 5). You'd like to have this node use npm 6 in _some_ projects, but other projects should still use node8+npm5.

With the node you want to duplicate already installed, first cd to the versions directory and rename the node. Then activate the newly renamed node and install the desired version of npm. And lastly, re-install node8 which gives you the "stock" npm.

```
cd $(nodenv root)/versions
mv 8.11.2{,+npm6}
nodenv shell 8.11.2+npm6
npm i -g npm
nodenv install 8.11.2
```

This gives you two node8 nodes, one with the stock npm5 and the other with npm6. nodenv won't mess with any global modules as you switch between nodes, so whatever npm you choose to install globally will remain with that node. (Unlike `n` which force-reinstalls the stock npm each time you switch nodes 😦 )

Of course, you can name the node whatever you like. I find the "+..." style to be pretty clear to distinguish from the default name. I've used this setup successfully for quite a while (especially back during the npm2 -> npm3 transition).

Of course, you can extrapolate this to any global module setup you like, doesn't need to be specific to npm.

**Comment by hjdarnel** [comment]
Thanks @jasonkarns, that sounds exactly like what I want!
