### ISSUE TITLE
Respect a .nvmrc file

### ISSUE THREAD

**Issue by joelzimmer** [nodenv/nodenv#116]
I'm not sure if this already exists, but can `nodenv` support `.nvmrc` files in the same way it supports a `.node-version` file - it may allow for easier migrations in the future.

**Comment by joelzimmer** [comment]
Bump?

**Comment by n8agrin** [comment]
@joelzimmer @jasonkarns have a look at https://github.com/ouchxp/nodenv-nvmrc. I was after the same thing and found that plugin.

**Comment by jasonkarns** [comment]
closing with @ouchxp's plugin as the solution.
