### ISSUE TITLE
Nodenv no such command `sh-'

### ISSUE THREAD

**Issue by sptndc** [nodenv/nodenv#137]
```
nodenv: no such command `sh-'
bash: eval: line 148: syntax error near unexpected token `rehash'
bash: eval: line 148: `  rehash|shell)'
```

This error after I installed nodenv via Linuxbrew.

**Comment by jasonkarns** [comment]
What command is triggering this output?

Can you also try running [nodenv-doctor](https://github.com/nodenv/nodenv-installer#nodenv-doctor) and including the output here or in a gist?

```
# with curl
curl -fsSL https://github.com/nodenv/nodenv-installer/raw/master/bin/nodenv-doctor | bash

# alternatively, with wget
wget -q https://github.com/nodenv/nodenv-installer/raw/master/bin/nodenv-doctor -O- | bash

# with npx/npm
npx -p @nodenv/nodenv-installer nodenv-doctor
```

**Comment by jasonkarns** [comment]
I'm going to close this for now, but if this is still an issue, please paste your output from `nodenv init -`, include what shell you're using, and preferably try the nodenv-doctor script as mentioned above. Thanks!
