### ISSUE TITLE
[Feature] Automatic install of required version

### ISSUE THREAD

**Issue by NHuebner1983** [nodenv/nodenv#143]
Possible to add a variable or something to automatically install when nodenv is stopped for a version that isn't installed?

Example:   10.15.0 is installed
Repo wants:   10.16.2
Nodenv halts:  10.16.2 is not installed

Maybe a bash_profile variable like NODENV_AUTO=1 or something?

Thanks!

**Comment by jasonkarns** [comment]
`nodenv version || nodenv install` will do that for you

That could be written as a plugin hooking into the `exec` or `version-name` hooks
