### ISSUE TITLE
npm tries to install to system directory

### ISSUE THREAD

**Issue by husam212** [nodenv/nodenv#149]
When I try to `npm install -g nodemon` for example, it fails because of permissions, below is the full log.

[2019-11-25T23_22_37_398Z-debug.log](https://github.com/nodenv/nodenv/files/3889229/2019-11-25T23_22_37_398Z-debug.log)

**Comment by Yuhsak** [comment]
By default, npm which installed by nodenv will automatically handles its package installation path if the --global option is set.
It will install modules into `.nodenv/versions/{VERSION}/lib/node_modules` normally.

You should make sure that your current using npm is under the control of nodenv at first.

1. `which npm`
Does this shows something like `.nodenv/shims/npm` ?

2. `nodenv which npm`
Does this shows something like `.nodenv/versions/{VERSION}/bin/npm`?

If the execution result of above commands seem to be OK, your npm global prefix is probably configured in somewhere (almost cases at $HOME/.npmrc).

See the output of `npm config ls` to check all configuration values currently set to your npm.
If this output includes the **prefix** value, that means that your npm is configured to install all modules under the path set by **prefix** value when --global option is specified.

I recommend you to check your npm configs once anyway.
Normally it's stored at `$HOME/.npmrc`, but could be found multiple locations in some cases like below.

- $NPM_CONFIG_USERCONFIG
- $NPM_CONFIG_GLOBALCONFIG
- /path/to/my/project/.npmrc
- $PREFIX/etc/npmrc

See also:

- https://docs.npmjs.com/misc/config
- https://docs.npmjs.com/files/npmrc

**Comment by husam212** [comment]
npm was under the control of nodenv, but prefix was set to some system path, all good now.

Thanks @Yuhsak.

**Comment by jasonkarns** [comment]
Thanks @Yuhsak!

@husam212 I'm going to add this npm-prefix detection to nodenv-doctor so that this issue is easily caught for other people as well.
