### ISSUE TITLE
exec -a with unqualified path causes memory corruption in older nodejs versions

### ISSUE THREAD

**Issue by mgabeler-lee-6rs** [nodenv/nodenv#151]
Yes, the title of this ticket sounds utterly bizarre, but I've finally traced down a super-bizarre problem.

The symptom:

Running `node -e ""` (or even `--help`) runs the repl instead of what you told it to, and then if you exit the repl it dies with `SIGABRT`.

The super-bizarre cause I found:

OpenSSL tries to dlopen itself to keep certain things active for the life of a process.  The code that does this does not seem to expect to be statically linked into a binary the way `node` does it, and so it decides it should `dlopen` `libnode.so`.

If you happen to have a system copy of that file around, it will find it and dlopen it.

Depending on details of versions, this seems to corrupt various bits of memory for the "real" node binary you're running.  I suspect this is due to re-running some static initializers in a way that causes several global variables to be reset.

However, if you give `argv[0]` as a qualified (even relative) path to the binary, OpenSSL calls `dlopen` on the actual filename, and the memory corruption disaster is avoided.

In newer versions of nodejs, this has been fixed by building OpenSSL with a flag to disable this `dlopen` behavior, but for node versions older than 10.17.0, this is unavailable.

Upstream info:
* https://github.com/nodejs/node/pull/28045
* https://github.com/openssl/openssl/pull/6725
* https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V10.md#2019-10-22-version-10170-dubnium-lts-bethgriggs -- `deps: dlloads node static linked executable`
  * https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V12.md#2019-08-06-version-1280-current-bridgear -- also fixed in 12.8.0
  * Older releases do not have this fix available

I'm not sure how "safe" it is to replace `exec -a "$NODENV_COMMAND" "$NODENV_COMMAND_PATH" "$@"` with `exec -a "$NODENV_COMMAND_PATH" "$NODENV_COMMAND_PATH" "$@"`, but that would avoid the issue for the affected nodejs versions.

**Comment by jasonkarns** [comment]
I very much appreciate the depth of information you've included in this issue. However, changing such a core component of nodenv has me a bit nervous. We can't be certain what wide-ranging impact it would have. And since you've noted that it has been fixed in recent versions of node, the benefit is limited and only shrinking as time goes on.

For those reasons, I'll opt to close this for now.
