### ISSUE TITLE
random default node version of 10.19.0 without installing it

### ISSUE THREAD

**Issue by pseudokoder** [nodenv/nodenv#164]
I just installed Nodenv today and I've never used it before.  I followed the installation steps.  After Nodenv was fully installed I used `nodenv install 12.18.0` to install the version I wanted.  No other versions have been installed prior to this, verified by running the nodenv-doctor; however, when I then attempted to start using node and npm I noticed that the node version from `node -v` was `v10.19.0`.  So I checked `nodenv version` which said `system (set by /home/jw/.nodenv/version)`.  

`nodenv versions` gave me this 
`*system (set by /home/jw/.nodenv/version)`
` 12.18.0`

I thought maybe I just needed to set the version to what I wanted so I used `nodenv global 12.18.0` and it worked until I rebooted my system which then reset it back.

I'm not sure if I'm doing something wrong or if I'm just not understanding the documentation.  Please help thanks!

**Comment by jasonkarns** [comment]
I'm sorry you're having trouble. Can you post the output of nodenv-doctor (ideally from a clean shell environment)?

A few things:
- installing a node with nodenv doesn't activate it, it just installs it. So after installing a node (no matter now many you have), you'll typically still need to select it with `nodenv global`, `nodenv local` or `nodenv shell`
- the node v10 is likely coming from your system; so it was likely installed outside of nodenv (via homebrew or manual installation or apt-get or something)
- when you say the reboot "reset it back" i'm not sure what you mean. `nodenv global` reads/writes to the _file_ at `$(nodenv root)/version`. rebooting your system wouldn't change the contents of that file. though if nodenv isn't installed correctly (ie, it's not part of your shell initialization), then a new shell environment (like after a reboot) would _appear_ as if things had changed. nodenv-doctor should report common installation issues (nodenv missing from path, nodenv shims missing from path, etc)

**Comment by pseudokoder** [comment]
Sorry, I accidentally closed this issue.

I tried running `nodenv global 12.18.0` again last night before shutting down and now this morning it seems to be working.  Running `node -v` gives me `v12.18.0`.  So I must have done something wrong in the beginning.

Here is the output from nodenv-doctor:
`$ curl -fsSL https://github.com/nodenv/nodenv-installer/raw/master/bin/nodenv-doctor | bash
Checking for `nodenv' in PATH: /home/jw/.nodenv/bin/nodenv
Checking for nodenv shims in PATH: OK
Checking `nodenv install' support: /home/jw/.nodenv/plugins/node-build/bin/nodenv-install (node-build 4.9.0)
Counting installed Node versions: 1 versions
Auditing installed plugins: OK`

As for the v10.19.0, unless it was part of the fresh install of the Pop!_OS it hasn't been installed before.  I only recently installed the OS a couple of days ago and the only things I've set up so far are my shell and vim environment.

When I said "reset it back" I could've been mistaken.  I remember using one of the commands from the Readme.md to set the node version to 12.18.0.  Maybe I didn't do it right the first time.

**Comment by jasonkarns** [comment]
Quick primer on the way nodenv works:

- nodenv works by having shims for `node` and `npm` (and any globally installed npm packages) that exist "first" in your PATH
- when you invoke `node`, its the shim that gets invoked which is then responsible for determining which version of node to run (and therefore which actual executable on disk to exec)
- it first checks if `NODENV_VERSION` env var is set. if it is that's the node version it uses. (`nodenv shell` corresponds to setting/unsetting this env var; as an env variable, it's only set for the lifetime of the shell. if you reboot or switch terminal panes/windows/tabs/etc, you'll be in another shell without that env var). this env var is useful for temporarily running a command or a project on a different node version
- if `NODENV_VERSION` isn't set, the shim starts looking for `.node-version` files in the current working directory and up through ancestors to root `/`. the first one it finds, that's the node version it uses. (`nodenv local` corresponds to this level of lookup. that command is used to _read/write_ a .node-version file in current working directory). this is the most common use of nodenv, by allowing a project to specify exactly which node it should run on
- if a `.node-version` file isn't found, the shim will check `$(nodenv root)/version` and use that file to determine the node version to use. (`nodenv global` corresponds to reading/writing to this file). this is mostly a convenience to specify one's "default" node to use when not in an app/project
- if `$(nodenv root)/version` doesn't exist, then nodenv falls back to the pseudo default version `"system"`; which is basically the same as nodenv's shims "getting out of the way" and just hoping that there's another `node` executable somewhere else in `PATH`. typically this is a node that is installed outside of nodenv; by homebrew, apt-get, bundled by the OS distro whatever

There are lots of caveats to this, of course, (some other filenames besides `.node-version`; some plugins will hook into this flow to read .nvmrc files or the `#engines` stanza of package.json, for instance; also there are some env vars that allow nodenv-local to look up a different directory tree other than `$PWD`, etc) but these are the broad strokes.


To be clear from your last comment, everything is working now?

**Comment by pseudokoder** [comment]
Wow!  Thank you so much for taking the time to provide such a thorough and clear explanation.  I have a much better idea of how to use those commands and I even learned some new things about the shell too.  

Yes, I believe everything is working now, and again thank you so much for your help.
