### ISSUE TITLE
npm i -g only works for cli packages, and not within node console

### ISSUE THREAD

**Issue by divrse** [nodenv/nodenv#167]
if I install a package using npm i -g, and then try to use it within the node console or within a script, it will fail to resolve that package.

Steps to reproduce.
1) ```npm i -g request```
2) Enter node console. ```node```
3) type ```const request = require('request')```

**Comment by jasonkarns** [comment]
This is not a limitation imposed by nodenv; node itself does not support requiring global modules. Global modules in node are global so as to be available as executables _outside_ a node project. They are not meant to be imported.

https://nodejs.org/api/modules.html#modules_loading_from_the_global_folders

As documented in the node docs, it _is_ possible by using `NODE_PATH` but it is a historical artifact and not a recommended feature.
