### ISSUE TITLE
ZSH : Install into .zprofile

### ISSUE THREAD

**Issue by coding-bunny** [nodenv/nodenv#169]
Hello,

I'm currently in a discussion with Jetbrains about their launcher for Rails apps not working properly on Ubuntu, as it cannot load nodenv properly due the way the installer suggests to set up your system.

When you follow the documentation, the output of the installation script suggest to place the `eval(nodenv init)` block inside your .zshrc file. Rubymine seems to be invoking all commands and operations using non-login shells, meaning the .zshrc file is never loaded in this case. This leads to problems when trying to run a Rails app locally with debugging saying that yarn for example cannot be found.

Would it be possible to update the script to recommend to install the nodenv initialization code and PATH handling in .zprofile instead? That way it should be picked up automatically by editors such as Rubymine when invoking scripts

**Comment by jasonkarns** [comment]
Hm, I'm not against it. I'll mention some other competing concerns, though.

- nodenv is a fork of rbenv, and we try to keep in sync with upstream as much as possible. If we decide to update the install instructions I would hope to have the same changes made to rbenv's docs.
- have you validated that placing the nodenv-init eval in .zprofile works as desired with rubymine?
- i'd also like to validate how this works with macOS considering that zsh is now the default shell but also that Apple Terminal has historically had "nonstandard" behavior regarding profile vs rc file initialization

But I'll reiterate that I'd still happily make the change if it does result in more consistent and friendly experience.

**Comment by coding-bunny** [comment]
Honestly, I'd leave it for now as is.
Rubymine fixed their issues in their new release, so all is good for me.
This was more an alternative to make everything work again.

**Comment by jasonkarns** [comment]
@coding-bunny i appreciate the issue all the same. Do you happen to have links to the ruby mine release notes if there is any reference to the relevant change? Hopefully this issue will help others if they encounter it.

**Comment by coding-bunny** [comment]
https://www.jetbrains.com/ruby/whatsnew/#ruby

Second point.
Only thing I could find outside digging through the support tickets.
