### ISSUE TITLE
Script to install/update nodenv on a shell (linux/mac)

### ISSUE THREAD

**Issue by flipkickmedia** [nodenv/nodenv#175]
```
#!/usr/bin/env bash
if [[ -d ~/.nodenv ]];then
  (cd ~/.nodenv && git pull)
else
  git clone https://github.com/nodenv/nodenv.git ~/.nodenv
fi

(cd ~/.nodenv && src/configure && make -C src)

echo 'export PATH="$HOME/.nodenv/bin:$PATH"' >> ~/.bash_profile
~/.nodenv/bin/nodenv init 2>&1 >/dev/null | egrep -v '#|^$' | tee -a ~/.bash_profile >/dev/null
. ~/.bash_profile
cd ~

if [[ ! -d "$(nodenv root)"/plugins ]];then
  mkdir -p "$(nodenv root)"/plugins
fi

if [[ ! -d "$(nodenv root)"/plugins/node-build ]];then
  git clone https://github.com/nodenv/node-build.git "$(nodenv root)"/plugins/node-build
else
  cd "$(nodenv root)"/plugins/node-build
  git pull
fi

curl -fsSL https://github.com/nodenv/nodenv-installer/raw/master/bin/nodenv-doctor | bash

echo "nodenv setup and updated"
```

**Comment by jasonkarns** [comment]
Thank you for sharing! Was there a particular use case you had intended to share this for?

(Quick notice, the script above doesn't appear to take `nodenv root` into account until after the installation step. If a user has nodenv already installed, perhaps through homebrew, or uses a custom NODENV_ROOT, then this script could result in cloning nodenv and shadowing existing installations.)

For a more robust installation script, you may be interested in [nodenv-installer](https://github.com/nodenv/nodenv-installer). I'd be happy to review any issues or improvements you have with that installer. (Though, it being a fork of rbenv-installer, would need to be careful with degree of drift.)

Thanks!
