### ISSUE TITLE
Question: How would I go about removing nodenv and all node instances from a server?

### ISSUE THREAD

**Issue by lustremedia** [nodenv/nodenv#184]
Would it just be:
cd
rm .nodenv -R

and remove the two lines form the .bash_profile?

Could this be added to the documentation?

**Comment by jasonkarns** [comment]
Any missing steps from the current readme?
- https://github.com/nodenv/nodenv#uninstalling-node-versions
- https://github.com/nodenv/nodenv#uninstalling-nodenv

(I'm going to go ahead and close this since it's been over a year, but happy to reopen if there are still concerns.)
