### ISSUE TITLE
homebrew formula broken

### ISSUE THREAD

**Issue by mgabeler-lee-6rs** [nodenv/nodenv#193]
The homebrew formula for nodenv has benn broken for over a month, and a PR to fix that has been open for almost that whole time, with multiple pings to the maintainers with no response.

I'm hoping by posting an issue in the main repo here it will catch someone's attention who has merge permissions in the other repo.

* https://github.com/nodenv/homebrew-nodenv/issues/96
* https://github.com/nodenv/homebrew-nodenv/pull/97

**Comment by jasonkarns** [comment]
Fixed with https://github.com/nodenv/homebrew-nodenv/pull/97
