### ISSUE TITLE
`nodenv install` tries to use python and fails on MacOS Monterey 12.3 and later and fails

### ISSUE THREAD

**Issue by debo** [nodenv/nodenv#196]
Hello there, as per subject, for some strange reason when I launch the command:
```shell
~ nodenv install 14.19.3
```
I get the following output:
```shell
~ nodenv install 14.19.3
Downloading node-v14.19.3.tar.gz...
-> https://nodejs.org/dist/v14.19.3/node-v14.19.3.tar.gz

WARNING: node-v14.19.3 is in LTS Maintenance mode and nearing its end of life.
It only receives *critical* security updates, *critical* bug fixes and documentation updates.

Installing node-v14.19.3...

BUILD FAILED (OS X 12.4 using node-build 4.9.81)

Inspect or clean up the working tree at /var/folders/sc/khld2gy54w7cdjtmk8ntk71r0000gn/T/node-build.20220525232800.76501.vssYfq
Results logged to /var/folders/sc/khld2gy54w7cdjtmk8ntk71r0000gn/T/node-build.20220525232800.76501.log

Last 10 log lines:
  2.7.18
  3.10.4
  3.7.13
  3.8.13
  3.9.12

Note: See 'pyenv help global' for tips on allowing both
      python2 and python3 to be found.
Missing or stale config.gypi, please run ./configure
make: *** [config.gypi] Error 1
```
The aforementioned log is [here](https://gist.github.com/debo/7bdc3d150eb3b3edae256bbba5f1318f)

Now, the errors in the logs are happening because of recent changes in macOS Monterey 12.3, discussed [here](https://github.com/pyenv/pyenv/issues/2379), and I am ok with that but, why `nodenv` is trying to invoke `python`? Moreover why this is happening only with NodeJS 14 and not with later versions (I didn't try to install EOL versions)? See my `nodenv versions` output:
```shell
~ nodenv versions
  16.14.2
  16.15.0
  17.9.0
  18.2.0
```

**Comment by ellierider** [comment]
Has anyone had success here? I am having similar issue:

```
✗ nodenv install 12.14.1
Downloading node-v12.14.1.tar.gz...
-> https://nodejs.org/dist/v12.14.1/node-v12.14.1.tar.gz

WARNING: node-v12.14.1 is in LTS Maintenance mode and nearing its end of life.
It only receives *critical* security updates, *critical* bug fixes and documentation updates.

Installing node-v12.14.1...

BUILD FAILED (OS X 12.4 using node-build 4.9.86)

Inspect or clean up the working tree at /var/folders/m5/zd4pr2dd0k77ppn9b9qq8s5w0000gn/T/node-build.20220721194155.77016.RNXmgS
Results logged to /var/folders/m5/zd4pr2dd0k77ppn9b9qq8s5w0000gn/T/node-build.20220721194155.77016.log

Last 10 log lines:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
4e8eac|OK  |    90MiB/s|/private/var/folders/m5/zd4pr2dd0k77ppn9b9qq8s5w0000gn/T/node-build.20220721194155.77016.RNXmgS/node-v12.14.1.tar.gz

Status Legend:
(OK):download completed.
/var/folders/m5/zd4pr2dd0k77ppn9b9qq8s5w0000gn/T/node-build.20220721194155.77016.RNXmgS/node-v12.14.1 /var/folders/m5/zd4pr2dd0k77ppn9b9qq8s5w0000gn/T/node-build.20220721194155.77016.RNXmgS ~/Sites/my-website
Please use Python 2.7
Missing or stale config.gypi, please run ./configure
make: *** [config.gypi] Error 1```

**Comment by snim2** [comment]
The work-around I used was to install [`pyenv`](https://github.com/pyenv/pyenv), then use `pyenv` to install Python 2.7.18 and then try again with `nodenv install 12...`

**Comment by debo** [comment]
What chip do you have? I couldn’t compile 2.7 on the M1 Pro at the time.

**Comment by jasonkarns** [comment]
I'm going to close this because it's not actually an issue with nodenv itself. At best, it would be an issue with node-build, but it's not an issue with node-build, either. node-build simply triggers node's own compilation. (node-build doesn't trigger python, node's own compilation does) If node itself can't compile on the target system, node-build can't do anything about that.

**Comment by nonzer0** [comment]
So I know this is closed but does anyone know why nvm would be able to install these older versions of node w/o issue?

**Comment by jasonkarns** [comment]
I don't think nvm compiles from source (not confident in this). And depending on the age of the build def, it's possible the version you're working with is before when node-build gained the precompiled binary support.

If nodejs still has the binaries, you can just unpack one into $(nodenv root)/versions/
