### ISSUE TITLE
No Debian / Ubuntu package available in the official repositories

### ISSUE THREAD

**Issue by leggiero** [nodenv/nodenv#208]
Hi,

Thanks for providing this amazing software.

The [README.md](https://github.com/nodenv/nodenv/blob/05ad905e828297acd3e1969b5eae8fc647a6cf26/README.md?plain=1#L173) says that nodenv can be installed with the apt package manager:

`$ sudo apt install nodenv`

But nodenv is NOT available in Debian nor Ubuntu default repositories:
- [Debian package search for nodenv](https://packages.debian.org/search?keywords=nodenv&searchon=names&suite=all&section=all)
- [Ubuntu package search for nodenv](https://packages.ubuntu.com/search?keywords=nodenv&searchon=names&suite=all&section=all)

Could you, please update the [README.md](https://github.com/nodenv/nodenv/blob/master/README.md) by removing this information or providing an alternative approach?

Thanks a lot!

**Comment by jasonkarns** [comment]
correct, thank you! this was an inadvertent side effect of the latest pull from rbenv upstream

**Comment by mendhak** [comment]
Ah that's a shame it's been removed, it was a very convenient and useful way of installing this tool. 
What would be the alternative to use for Ubuntu/Debian? eg the nodenv-installer?

    curl -fsSL https://github.com/nodenv/nodenv-installer/raw/HEAD/bin/nodenv-installer | bash

**Comment by jasonkarns** [comment]
Yeah. That or homebrew, which supports Linux these days. Or the vanilla git-clone installation.

Though if you'd be able and willing to create the packaging for Debian, that would be amazing. I'm a Mac user myself so I'd be in foreign waters trying to do it myself.

**Comment by mendhak** [comment]
Understood at the very least maybe we could get some documentation updated. Note that homebrew on Linux exists but isn't a great idea as it's quite destructive. It's safer to just leave it at the vanilla instructions.
