### ISSUE TITLE
Create Debian installation packages

### ISSUE THREAD

**Issue by jasonkarns** [nodenv/nodenv#210]
nodenv is NOT available in Debian nor Ubuntu default repositories:
- [Debian package search for nodenv](https://packages.debian.org/search?keywords=nodenv&searchon=names&suite=all&section=all)
- [Ubuntu package search for nodenv](https://packages.ubuntu.com/search?keywords=nodenv&searchon=names&suite=all&section=all)

_Originally posted by @leggiero in https://github.com/nodenv/nodenv/issues/208_

**Comment by jasonkarns** [comment]
I'm going to close this as the creation of packages for managers is technically outside the scope of this project. Though I would be grateful if someone were to create nodenv packages for debian and ubuntu. I personally don't have the time or experience. (I'm primarily on macOS)

**Comment by dayeye2** [comment]
> nodenv is NOT available in Debian nor Ubuntu default repositories:
> 
> * [Debian package search for nodenv](https://packages.debian.org/search?keywords=nodenv&searchon=names&suite=all&section=all)
> * [Ubuntu package search for nodenv](https://packages.ubuntu.com/search?keywords=nodenv&searchon=names&suite=all&section=all)
> 
> _Originally posted by [@leggiero](https://github.com/leggiero) in [#208](https://github.com/nodenv/nodenv/issues/208)_

Workflow

**Comment by jasonkarns** [comment]
> Workflow

@dayeye2 excuse me?
