### ISSUE TITLE
Not respecting makefile

### ISSUE THREAD

**Issue by gedw99** [nodenv/nodenv#211]
example

 ``` 
run:
     nodenv install 18.14.0
     nodenv shell 18.14.0 && make build-doc


``` 

output of make run
``` 
nodenv install 18.14.0
nodenv: /Users/apple/.nodenv/versions/18.14.0 already exists
continue with installation? (y/N) N
nodenv: shell integration not enabled. Run `nodenv init' for instructions.
```

**Comment by jasonkarns** [comment]
What makefile are you expecting to be respected? There is no makefile in nodenv that has any build-doc target.

**Comment by jamesdh** [comment]
@gedw99 This is how Make is intended to work, it has nothing to do with nodenv. Each line operates in its own independent shell. When your second command is executed, it's as if it's operating in a shell that has not yet had nodenv installed in. 

If you changed it to something like the following, it would likely work: 
```Makefile
run: 
    nodenv install 18.14.0 && nodenv shell 18.14.0 && make build-doc
```

This issue can be closed.
