### ISSUE TITLE
RBENV reference in the README

### ISSUE THREAD

**Issue by eclectic-coding** [nodenv/nodenv#212]
Looks like there is a residual reference to `rbenv` in the `README`, in the [Installing Node Versions](https://github.com/nodenv/nodenv#installing-node-versions) section: 

```
Set a Node version to finish installation and start using commands nodenv global 18.14.1 or rbenv local 18.14.1
```

I will be glad to submit this small PR if you like.

Thanks for the great product.

**Comment by jasonkarns** [comment]
Yeah that would be great!

**Comment by ashemedai** [comment]
Not just that, there's `rbenv-versions` in the libexec directory as well.
