### ISSUE TITLE
nodenv init creates duplicates in PATH

### ISSUE THREAD

**Issue by RichardFevrier** [nodenv/nodenv#221]
Hello, adding `nodenv init - | source` in `config.fish` adds twice the `shims` path (same issue on `rbenv` but not on `pyenv`).

**Comment by jasonkarns** [comment]
The conversation for this issue will take place on the rbenv repo so we don't have parallel conversations: https://github.com/rbenv/rbenv/issues/1573

**Comment by jasonkarns** [comment]
closing per above. any changes that land in rbenv upstream will make there way here eventually anyhow
