### ISSUE TITLE
nodenv org

### ISSUE THREAD

**Issue by jasonkarns** [nodenv/nodenv#27]
I spoke with @wfarr about the nodenv org. Apparently, he wasn't the org's creator, but was invited as a member. He has invited @OiNutter as an owner so we should be able to begin using the nodenv org for nodenv and all the related plugins.

Opening this issue as a place for discussion and tracking the 'migration'

@OiNutter once you are in the nodenv org, would you mind adding us maintainers, as well?

**Comment by OiNutter** [comment]
Ok, you guys are added now. Is the intention to replace the @wfarr's version of nodenv with this one? Or try and merge the 2 together?

Also thanks for keeping on top of the issues etc with this guys, sorry I've not really been around to help out. You guys are doing a great job.

**Comment by jasonkarns** [comment]
I'm curious what @wfarr's opinion is. Are there features of his that aren't in ours? If so we could merge those features in. Structurally, I would prefer to modify our nodenv as little as possible since it's been kept very close to rbenv; which has enabled us to keep up to date with rbenv changes and merging in those changes from 'upstream'. But any features that wfarr's nodenv has that ours doesn't could certainly be discussed.

As for the destination of the two repositories, my personal preference is to move @OiNutter's nodenv into the nodenv org (along with all associated plugins that we intend to maintain). @wfarr's nodenv can be spun back out as a personal repo? Or kept under nodenv with a different name? Or removed altogether depending on his goals for that project. I think most of this hinges on his opinions and goals.

**Comment by jasonkarns** [comment]
thoughts @wfarr on the fate of your nodenv?

And what of the existing members of the org? @ericanderson @rtgibbons @xdissent

Are you folks interested in remaining in the nodenv org and helping maintain @OiNutter's nodenv and related plugins?

**Comment by wfarr** [comment]
I have no strong opinions either way. Unless anyone has any objections, I'm fine completely sunsetting my nodenv and pointing people at the one that's actively maintained.

**Comment by jawshooah** [comment]
I'm fine with migrating my plugins and the homebrew-nodenv tap to the nodenv org.

**Comment by jasonkarns** [comment]
Do we have any idea of who, if anyone, is pointing to nodenv/nodenv? The
old homebrew formula was pointing to wfarr/nodenv and not to the nodenv
org's fork. Should it be safe to just force-push the new nodenv into
nodenv/nodenv?

Or should we attempt to delete nodenv/nodenv, and then have @oinutter
transfer oinutter/nodenv into the org?

**Comment by wfarr** [comment]
Don't delete it please. Just rename it and update the README to explain the deprecation and point to the new project. Someone may still be using it, so we should keep the code around for posterity's sake.

**Comment by jasonkarns** [comment]
fair. I was thinking that the one under your username would remain for
sure. that's why i was curious how popular nodenv/nodenv repo was (vs
wfarr/nodenv). But renaming is a better direction, anyway

**Comment by jasonkarns** [comment]
@wfarr care about the name? 
`nodenv-old` `nodenv-deprecated` `nodenv-wfarr`

**Comment by jasonkarns** [comment]
Any of the @nodenv/owners (@wfarr, @OiNutter, @ericanderson) care to either make me an admin or rename the nodenv/nodenv repo themselves?

My vote is to rename it as wfarr-nodenv. nodenv-wfarr could be confusing as it follows the same structure as nodenv plugins. I might even suggest just naming it `wfarr`, `old` or `deprecated` since it would be under the nodenv org as nodenv/wfarr (or nodenv/old, nodenv/deprecated)

**Comment by jawshooah** [comment]
@jasonkarns I think `wfarr-nodenv` works. `nodenv` should definitely be in the name somewhere to prevent confusion.

**Comment by OiNutter** [comment]
@jasonkarns I've renamed the repo to wfarr-nodenv and I've also added you to the Administrators team, (Renamed from Owners because GitHub have changed a load of stuff and suggested it was a good idea) I've also migrated the Administrators team to the new permissions.

**Comment by OiNutter** [comment]
Is there anything else or can we close this issue now?

**Comment by jasonkarns** [comment]
I think we'll need to keep this open as we continue through the rest of the process.

1. this repo now needs transferred to nodenv/nodenv (https://help.github.com/articles/transferring-a-repository/#transferring-from-a-user-to-an-organization)
2. current maintainers on this repo need added as members of the nodenv group (who?)
3. we need to decide which plugins we'll accept ownership of. I'm of the opinion we should accept all of the nodenv plugins that are authored by current maintainers, but I don't want to presume.

@OiNutter, you're the only one who can complete # 1, and you're the only one who knows who all are current maintainers here. Could you list them?

**Comment by jasonkarns** [comment]
@OiNutter I see that I'm a member of the Administrators team, but I still only have Member rights, not Admin rights. I attempted to transfer the first of my repos to the nodenv org, but the transfer failed because I'm not an admin of nodenv.

**Comment by jasonkarns** [comment]
@OiNutter can you make me an admin in the nodenv org? (see previous comment)

**Comment by jasonkarns** [comment]
ping @OiNutter ^^

**Comment by jasonkarns** [comment]
alternatively @ericanderson, are you able to add me as an admin (see https://github.com/OiNutter/nodenv/issues/27#issuecomment-167722292)

**Comment by OiNutter** [comment]
Done, sorry!

**Comment by jasonkarns** [comment]
@OiNutter thanks! are you also able to transfer nodenv, node-build, and nodenv-vars to the nodenv org soon?

**Comment by OiNutter** [comment]
Just moved them now
