### ISSUE TITLE
Determine plugins of which to accept ownership

### ISSUE THREAD

**Issue by jasonkarns** [nodenv/nodenv#36]
Opening this thread to discuss which existing nodenv plugins the nodenv org will take ownership of.

I'm assuming that we just take ownership of any plugins authored by members of the org, but I don't want to make the decision unilaterally.

**Comment by jasonkarns** [comment]
Any objections to the nodenv organization accepting ownership and maintenance of the following nodenv plugins? (just listing those that I own)

- [nodenv-aliases](https://github.com/jasonkarns/nodenv-aliases)
- [nodenv-package-rehash](https://github.com/jasonkarns/nodenv-package-rehash)
- [nodenv-each](https://github.com/jasonkarns/nodenv-each)
- [node-build-update-defs](https://github.com/jasonkarns/node-build-update-defs)

**Comment by jawshooah** [comment]
No objection here. I'll offer mine up as well:

- [nodenv-npm-migrate](https://github.com/jawshooah/nodenv-npm-migrate)
- [homebrew-nodenv](https://github.com/jawshooah/homebrew-nodenv)
- [homebrew-nodenv-head-only](https://github.com/jawshooah/homebrew-nodenv-head-only)
- [nodenv-default-packages](https://github.com/jawshooah/nodenv-default-packages)

**Comment by jasonkarns** [comment]
@jawshooah I added you as an owner to the nodenv org so that you can transfer your plugins/taps

There hasn't been any discussion around who will be owners long term (I was only just today given access so that I could transfer my plugins).

**Comment by jasonkarns** [comment]
@charlesbjohnson are you interested in moving nodenv-update into the nodenv org?

**Comment by charlesbjohnson** [comment]
Yes, I'll offer:
- [nodenv-update](https://github.com/charlesbjohnson/nodenv-update)

**Comment by jasonkarns** [comment]
@charlesbjohnson invited

**Comment by jasonkarns** [comment]
Votes from @OiNutter @jawshooah @ianks and @charlesbjohnson as to whether we propose/accept [nodenv-package-json-engine](https://github.com/hurrymaplelad/nodenv-package-json-engine into the) into the org?

**Comment by jawshooah** [comment]
@jasonkarns Fine by me as long as @hurrymaplelad is alright with it.

**Comment by OiNutter** [comment]
Looks good to me

**Comment by charlesbjohnson** [comment]
@jasonkarns :+1: for [nodenv-package-json-engine](https://github.com/hurrymaplelad/nodenv-package-json-engine).

**Comment by jasonkarns** [comment]
invited @hurrymaplelad into org and to transfer nodenv-package-json-engine 

https://github.com/hurrymaplelad/nodenv-package-json-engine/issues/12
