### ISSUE TITLE
nodenv org discussions

### ISSUE THREAD

**Issue by jasonkarns** [nodenv/nodenv#40]
thoughts on a communication channel? I quickly opened a gitter.im room https://gitter.im/nodenv since I figured that would be a lower barrier of entry than a slack group.

also reset the waffle board with the new org: https://waffle.io/nodenv/nodenv  The waffle board so far has all the repos that are currently in the org and is a nice way to see all of the issues/prs across the org on one board. It doesn't change anything with github, so no one is forced to use it. Personally, I like being able to see all the repos' issues and prs in one place.

**Comment by OiNutter** [comment]
A slack group would probably be preferable to me as I'm already using that for work so easier to have it open and pay attention during the day, might actually manage to get back to being more involved with this as I've just been too busy to get anywhere near of late.

Go with whatever works for the most people though.

**Comment by jawshooah** [comment]
I've never used slack, so I can't comment on it. We do use gitter.im over in @caskroom though, so I'm familiar with the interface and usually have the native app open.

**Comment by ericanderson** [comment]
I'm a fan of slack but I'm also not likely to be an active contributor.

**Comment by jasonkarns** [comment]
Does slack have the ability for people to join without an invite yet? Last I checked, an invite was needed to join a slack team. If that has changed, I'd be fine with slack over gitter. Otherwise, I think gitter works better as a team channel since anyone can join without an invite and begin participating.
