### ISSUE TITLE
Prefer local node_modules/.bin?

### ISSUE THREAD

**Issue by hurrymaplelad** [nodenv/nodenv#45]
Say I have 2 projects that use different versions of `coffee-script`, and I'd like `$ coffee` to run the local version from each project directory.  I'd also like to globally install some version of `coffee-script` so Atom plugins don't explode.  Is this possible?

I got stuck at the point where shims are added first in my path.  Seems like a globally installed module always takes precedence...

**Comment by jasonkarns** [comment]
I have an idea for a plugin to make this possible, but at present it is not. It's not related to nodenv in any way. Local node_modules bins simply aren't on the path, and a non-nodenv installation isn't any different. There are alternatives, however. 

1. Add `./node_modules/.bin` to your `PATH`. Though there are security reasons to avoid this.
2. `$(npm bin)/coffee` will run the local coffee. And npm-bin works anywhere in the project (not just at root).
3. Use npm run-scripts. When an npm script is invoked via `npm run foo`, npm prepends `$(npm-bin)` to your `PATH`. So scripts can invoke any locally installed bin without the need to prefix it.

    ``` json
    "scripts": {
      "compile": "coffee"
    }
    ```

  Now `npm run compile` will use your local coffee.


The complication for making a plugin for this is finding a way to make nodenv aware of all your local node_modules. It can't shim what it doesn't know about. Best I can think of so far, is that the plugin prepends `$(npm bin)` to the `PATH` during the `exec` hook. But this would only work for modules that have been installed globally and are thus shimmed. So for any locally-installed bin, one would need to install it globally as well. Then the global shim would trigger nodenv, and the exec hook could prepend local bin path.

**Comment by hurrymaplelad** [comment]
Thanks for all the thoughts!

I'm in bucket #1.  I've already added ./node_modules/.bin to my path, but I can't give them precedence over globally installed modules which nodenv pretends to my path.

Any thoughts on configuring where in the path the shims are added?

**Comment by jasonkarns** [comment]
nodenv alters `PATH` when the output of `nodenv init` is sourced (or evaled depending on your setup)

So you just need to prepend `./node_modules/.bin` to PATH *after* you've invoked nodenv-init

**Comment by jasonkarns** [comment]
Closing since there's a [workaround](https://github.com/nodenv/nodenv/issues/45#issuecomment-183363153):
