### ISSUE TITLE
New MacBook

### ISSUE THREAD

**Issue by jdcauley** [nodenv/nodenv#51]
New MacBook
Installed Nodenv via Homebrew

```npm: command not found```

![](https://d1zjcuqflbd5k.cloudfront.net/files/acc_381205/KNNJ?response-content-disposition=inline;%20filename=Screen%20Shot%20on%202016-06-25%20at%2023%3A16%3A44.png&Expires=1466911388&Signature=S6Uqze-~e-br4a25B4TvbsTThtSaURJ9UpuS4QkkOIBk4Pl9~tuVwB~BZ0xz6zTehNYXYEgvb0Th8-KIKmnzRdf5Bmg9cFUSyvJef8KVJu2zmmIp7VNBLdb1-QoNZwsAJp-sy209hjFc1BG3gyFCZpHwhWKPNKQTU~jdFdrrvdE_&Key-Pair-Id=APKAJTEIOJM3LSMN33SA)

**Comment by jawshooah** [comment]
Did you follow the instructions in the `caveats` when you installed via Homebrew?

```
To enable shims and autocompletion add to your profile:
  if which nodenv > /dev/null; then eval "$(nodenv init -)"; fi
```

**Comment by jdcauley** [comment]
No my mistake, I'm very sorry

**Comment by jawshooah** [comment]
No worries! Glad to help 😸
