### ISSUE TITLE
Support x.x format version strings

### ISSUE THREAD

**Issue by robinjoseph08** [nodenv/nodenv#53]
Hey!

Is there any possibility of being able to support versions formatted like `0.12` or even `5`, where it would match the latest version installed that still matches the string prefix? I'm looking to move from `nvm` and `avn` (which do support this format) to `nodenv` but most of our repos are specified in this format which means nothing is working.

I'd be happy to submit a PR if this is something worth supporting!

Thanks!

**Comment by jasonkarns** [comment]
Short answer: no.

Helpful answer: use [nodenv-aliases](https://github.com/nodenv/nodenv-aliases) plugin

Longer answer:

It is the rbenv team's belief (and nodenv's by proxy) that a version file identity a specific and unambiguous version. (see https://github.com/rbenv/rbenv/pull/510 https://github.com/rbenv/rbenv/issues/328 https://github.com/rbenv/rbenv/pull/397 https://gist.github.com/fnichol/1912050#gistcomment-682506)

Further, the question of sharing nodenv-version files in repos is eye-brow raising. The goal of the version specifier is to be absolutely precise across all installations, dev and production. This type of precision only makes sense for apps; not libraries. Libraries should not be restricted to particular node versions for the same reason that libraries should not have shrinkwraps (and gems shouldn't have committed Gemfile.lock). Doing so implies a false sense of control that does *not* exist in the wild. As for apps, where one _does_ have such control, the goal and desire is not to be ambiguous, but to be strictly precise.

So if your repos are libs, I would strongly recommend removing the node-version files from version control. If they are apps, I would strongly recommend specifying a precise node version (including patch version). If I've failed to convince you of these approaches, then the nodenv-aliases plugin is for you! :)

*Caveat:* We are considering adding these short-version specifiers to node-build. However, they would only be available as shortcuts for installing the latest patch (or minor) version of a particular minor (or major) release. The install process would still name the version by its full version number.
