### ISSUE TITLE
Should auto install if node_version is present

### ISSUE THREAD

**Issue by Pyrolistical** [nodenv/nodenv#54]
I git cloned a project that already had a node_version file present, but I didn't have that particular version installed. When I tried to run `npm install` nodenv showed an error stating the required version was not installed. 

Instead of printing an error nodenv should just run `nodenv install ...` and then run `npm install` for real. 

This would make using nodenv seamless

**Comment by jawshooah** [comment]
We aim to maintain feature parity with `rbenv`, so this is out of scope and would be best implemented as a plugin, not as part of `nodenv` core. Feel free to take a swing at it yourself.
