### ISSUE TITLE
add a "Why choose nodenv over NVM?"

### ISSUE THREAD

**Issue by AlJohri** [nodenv/nodenv#62]
Hi. I love using nodenv. It's great to have the same interface across multiple languages (rbenv, pyenv, etc.).

I wish more people used it.

Can you add a quick "Why choose nodenv over NVM" just like rbenv does in their README?

Thanks!

**Comment by AlJohri** [comment]
spoke too soon, I see there's already something in the [Wiki](https://github.com/nodenv/nodenv/wiki/Alternatives). Still would be great to link it in the README. Thanks!

![screen shot 2016-12-29 at 7 28 11 pm](https://cloud.githubusercontent.com/assets/2790092/21557612/f5837eaa-cdfc-11e6-8945-56beaa8d3471.png)

**Comment by jasonkarns** [comment]
Yes! A "why choose nodenv" blog post is been in draft status forever.

**Comment by olegantonyan** [comment]
I chose nodenv over nvm because it doesn't freeze my shell on start up (~1 sec). There are tons of such issues with nvm https://www.google.com/search?q=nvm+slow+startup&gws_rd=cr&hl=en&num=30

**Comment by joshmorel** [comment]
In the wiki it points out that many don't work on Windows. Does this work on Windows? It would at least need Cygwin and I could try it but any comment from the maintainers? There's nothing on the main page about Windows. Also, just to note that n doesn't do separate node_modules per version - a big issue IMHO right now.

**Comment by jasonkarns** [comment]
No, nodenv doesn't work on windows, though I'd be surprised if it didn't work with mingw/msys. (I'd also expect it to work with cygwin but I've never tested.) Also curious if nodenv would work with the new bash shell on windows, but again, never tested.

nvs is a new version manager that _does_ work with windows.


I think you make a great point about separate node_modules. How each version manager handles npm and global node modules is a _huge_ differentiator. (Not only does `n` share node_modules, `npm` is *reinstalled* each time you switch. So you can't peg a specific version of npm to a node version!)

**Comment by AlJohri** [comment]
Would still love to see this blog post :)

On another note, here's a similar project that also uses shims: https://github.com/asdf-vm/asdf with https://github.com/asdf-vm/asdf-nodejs

**Comment by ouchxp** [comment]
Not entirely related to this. I have wrote a plugin that can detects the node version based on `.nvmrc`. Hope this helps for people trying to migrate from NVM
https://github.com/ouchxp/nodenv-nvmrc

**Comment by FranklinYu** [comment]
> In the wiki it points out that many don't work on Windows.

I’m also confused about this. If those libraries don’t work in native Windows environment but Cygwin or WSL is supported, then we don’t need to mention this at all, because most of those are written in Bash and inherently won’t work in PowerShell or CMD.exe. If any of them don’t even support Cygwin or WSL (the developer explicitly rejects to support) then we should explicitly point out which one, and provide link to that statement of “won’t fix”.

I could have just edited that Wiki page, but I thought it would be more polite to discuss here first.

**Comment by jasonkarns** [comment]
@FranklinYu yeah, that should probably be removed or re-worded. Especially because nodenv itself is bash-only. That note was originally made while I was just researching the differences between the various tools.

**Comment by jasonkarns** [comment]
Feedback welcome: https://github.com/nodenv/nodenv/wiki/Why-nodenv%3F
