### ISSUE TITLE
--version gives package.json error

### ISSUE THREAD

**Issue by jbcpollak** [nodenv/nodenv#70]
I have nodenv installed via Homebrew:

    brew install nodenv

and In my `.zshrc` file I have:

    eval "$(nodenv init -)"

When I run `nodenv --version` I get this output:

    $ nodenv --version
    grep: ../package.json: No such file or directory
    nodenv

**Comment by jasonkarns** [comment]
Legit. Seems like an update to the homebrew formula has the package.json file missing from the install.

**Comment by jasonkarns** [comment]
Fixed in master but won't be "fixed" via homebrew until a new version is tagged and published (and updated in homebrew)

**Comment by jasonkarns** [comment]
latest version has been deployed to homebrew!
