### ISSUE TITLE
Nodenv not installing correctly on KDE Mint Linux 18.1

### ISSUE THREAD

**Issue by thelukemccarthy** [nodenv/nodenv#71]
Hi

I have pulled down the latest version on nodenv (15-May-2017) and followed the instructions to install.

When I ran
`cd ~/.nodenv && src/configure && make -C src`  
I got the following error  
```
make: Entering directory '/home/luke/.nodenv/src'
gcc -fPIC     -c -o realpath.o realpath.c  
realpath.c:2:20: fatal error: stdlib.h: No such file or directory  
compilation terminated.  
Makefile:19: recipe for target 'realpath.o' failed  
make: *** [realpath.o] Error 1  
make: Leaving directory '/home/luke/.nodenv/src'`  
```
As the instructions state that nodenv should still work if this fails I just add nodenv to my path in .bashrc and then run the command  
`~/.nodenv/bin/nodenv init`
The out from that command is as follows
```
# Load nodenv automatically by appending
# the following to ~/.bashrc:

eval "$(nodenv init -)"`
```
I added eval `"$(nodenv init -)"` to the end of my .bashrc file and close all open terminals and opened a new terminal window. when I run the command
`type nodenv`
I get the result
```
nodenv is /home/luke/.nodenv/bin/nodenv
```
If I then run `nodenv init` I get the same result as before however running 
`type nodenv`
returns
```
nodenv is hashed (/home/luke/.nodenv/bin/nodenv)
```
If I manually run 
`eval "$(nodenv init -)"`
and then run 
`type nodenv`
I finally get the expected result and nodenv works as expected
```
nodenv is a function
nodenv () 
{ 
    local command;
    command="$1";
    if [ "$#" -gt 0 ]; then
        shift;
    fi;
    case "$command" in 
        rehash | shell)
            eval "$(nodenv "sh-$command" "$@")"
        ;;
        *)
            command nodenv "$command" "$@"
        ;;
    esac
}
```

below are the last three lines of my .bashrc file
```
export PATH="$HOME/.nodenv/bin:$PATH"
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"
```
Does anyone know what I'm doing wrong? Any help would be appreciated.

Luke

**Comment by thelukemccarthy** [comment]
OK I have resolved the problem, and as I expected, I didn't do it write.

When I was updating my .bashrc file I thought the line
```
eval "$(nodenv init -)"
```
was already added, but as I now see that was for rbenv (ruby).
Now I actually have `eval "$(nodenv init -)"` in my .bashrc file everything works perfectly.

I hope this might help someone else :D

**Comment by jasonkarns** [comment]
Thanks for the follow-up!
