### ISSUE TITLE
Issue with fish 2.6.0, needs backport from rbenv

### ISSUE THREAD

**Issue by rubenvarela** [nodenv/nodenv#74]
I stumbled upon this today after upgrading.

When loading fish, the message I'm getting is

    setenv: Too many arguments

This is also affecting pyenv and here is their pull request, https://github.com/pyenv/pyenv/pull/927

Copied the title from here which is where I found it, https://github.com/pyenv/pyenv/issues/926
And they also have this https://github.com/pyenv/pyenv/pull/924

**Comment by dkowis** [comment]
Not to zombie the issue, but I would super love a release with this, got the same problem :)

**Comment by jasonkarns** [comment]
released as v1.1.1 (was already in master for a while if using git as installation mechanism)
