### ISSUE TITLE
Hooks have undefined execution order

### ISSUE THREAD

**Issue by maxnordlund** [nodenv/nodenv#77]
They seem to be ordered by hook path, which makes sense. But then just be in the order of the [globbing](https://github.com/nodenv/nodenv/blob/master/libexec/nodenv-hooks#L59). Is there a way to control this order, without messing with the hook path?

**Comment by jasonkarns** [comment]
I don't believe so, no. Is there a case where you need a particular order? Or just need the hook order to be more deterministic?

**Comment by maxnordlund** [comment]
I have two hooks for supporting local binstubs and yarn global binaries (which actually live in ~/.config/yarn/global/node_modules/.bin). They are complicating right now, but they started to run in the correct order so I guess it depends in the inode number.

As long as it's deterministic I can make them run in the run correct order, right? Then that's more then enough for me.

**Comment by jasonkarns** [comment]
I did some quick searching, and apparently the POSIX spec dictates the ordering of a glob result be deterministically ordered. (based on the locale) http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_13_03

If we uncover a scenario where this is not the case, we can probably push a PR up to rbenv upstream to sort the hook list before processing. But until such a scenario is shown, I'm going to work on the assumption that the glob order is at least deterministic per the POSIX spec.

**Comment by maxnordlund** [comment]
Lovely, that's good enough indeed.
