### ISSUE TITLE
Use with npx

### ISSUE THREAD

**Issue by tylercollier** [nodenv/nodenv#79]
I just read [Introducing npx](https://medium.com/@maybekatz/introducing-npx-an-npm-package-runner-55f7d4bd282b) about the new binary `npx` that comes as part of npm 5.2+ (which comes with node 8). I wanted to use their "Executing one-off commands" example where they do `$ npx create-react-app my-cool-new-app` where it "installs a temporary create-react-app and calls it".

So I installed node 8. I did `nodenv global 8.0.0`. I upgraded npm to make sure I had 5.2. I then ran their example:

```
npx create-react-app real-world-discussions-demo
```

Output:
```
nodenv: create-react-app: command not found

The `create-react-app' command exists in these Node versions:
  4.2.3
```

Oops! I had already installed `create-react-app` globally in 4.2.3. But wait, I'm not trying to run a global command, right? That's the point of npx. After I deleted create-react-app out of 4.2.3, I ran the command again and it worked as shown in that medium post.

So my question is, why didn't this work as expected? It should have installed a temporary create-react-app in node 8 and called it, but instead it barfed, but that's exactly what npx is trying to prevent. The article mentions that npx should work well with nvm, nave, or n, but doesn't mention nodenv.

**Comment by jasonkarns** [comment]
Throwing in my initial first guesses without much research so... grain of salt. :)

When a module is installed globally, nodenv makes a shim for it. This shim is in your `PATH`. So according to a system `which foo` lookup, it will find the executable in nodenv's shims and report "Hey, we successfully found an executable matching `foo` in `PATH`. Cool." So my _suspicion_ is that `npx` simply checks to see whether the desired binary exists in `PATH`; assuming that if it does, it can just invoke it and skip the "temporary installation". (I'm still not clear on whether npx's installation of modules is temporary or permanent.)

However, as far as nodenv is concerned, the existence of the shim doesn't guarantee that the executable is installed for the given version. When the shim is actually executed, nodenv checks if the matching executable is installed for the currently active version. If it is, it executes it; hunky dory. If _not_, it does a search through all the installed nodes to see which versions _do_ have the desired executable; and then prints the helpful message that you saw.

> foo not found; foo exists in these nodes:

At present I don't have any more feedback for you, or comments for npx. I need to investigate further to confirm my suspicions before forming any opinions about next steps. But this is what I suspect is the problem. I'll keep this issue open as you/others dig deeper and hopefully shed more light on npx's behavior.

**Comment by tylercollier** [comment]
I'll close this for now. I suspect it's something npx would have to deal with, so I'll move it there. FWIW the creator of npx said [here](https://medium.com/@maybekatz/npx-has-no-explicit-support-for-any-version-managers-825fcc2f905f) that

> npx has no explicit support for any version managers. It does some installation and $PATH-manipulation work

I'm guessing it's a difference between nodenv using shims where the rest of the node managers work more globally.

**Comment by jasonkarns** [comment]
Yeah, to my knowledge most other version managers manipulate the `PATH` (and other env vars), whereas nodenv has static shims that live within an unmodified `PATH`, that do the bin lookup at invocation time.

Reopening to track conversation and for any further thoughts as people experiment.

**Comment by ELLIOTTCABLE** [comment]
Okay, I can't even get npx to *show up*, with Nodenv:

```
❯ ~ nodenv global 8

❯ ~ nodenv version 
8 (set by /Users/ec/.nodenv/version)

❯ ~ npx                     
zsh: command not found: npx

❯ ~ npm i -g npm 
/Users/ec/.nodenv/versions/8.1.4/bin/npm -> /Users/ec/.nodenv/versions/8.1.4/lib/node_modules/npm/bin/npm-cli.js
/Users/ec/.nodenv/versions/8.1.4/bin/npx -> /Users/ec/.nodenv/versions/8.1.4/lib/node_modules/npm/bin/npx-cli.js
+ npm@5.3.0
updated 1 package in 13.804s

❯ ~ [15s] which npm
/Users/ec/.nodenv/shims/npm

❯ ~ which npx
npx not found
```

Although, based on this Issue, it looks like it wouldn't work, even if I got it to install? :x

**Comment by jasonkarns** [comment]
Don't forget to `nodenv rehash` after installing global modules, otherwise you won't have the shim in your PATH.

**Comment by jbcpollak** [comment]
I'm running into this problem with `npm-merge-driver`, which is a bit of a problem because merging package-lock.json files would be a huge win. 

You can get npx to "work" by using the --ignore-existing flag, but that's a ton slower than just letting npx call the locally installed version.

I'm not sure how this would work technically, but ideally it would be great if nodenv could be npx aware (which seems more reasonable than the other way around) so that nodenv could allow npx to execute the locally installed version from another node version, or perhaps just ignore the local version _only if_ its the shim that's going to error out.

**Comment by ELLIOTTCABLE** [comment]
Might I suggest `nodexenv` or something, that we could then alias to `npx` locally? `(=`

**Comment by tylercollier** [comment]
I didn't use npx for a long time. Recently, to launch local executables within projects, I've been typing `node_modules/.bin/EXECUTABLE_NAME`, and then a friend mentioned npx, and I had never realized that npx worked that way (check for a file in `node_modules/.bin` for you first before installing a temporary copy). Since the time he mentioned it, I've been using npx without issue for a while, and hadn't even realized that perhaps I'm using a version from a different version of node. As in, perhaps I am using node 10 for some project, then I type `npx SOME_COMMAND`, and perhaps it's executing that with e.g. node 8's npx? How can I check? If it seems to be working for me, should I not worry? Because I'm guessing even though it may seem to work, it might hose me someday due to version mismatches. I'm happy to help but I'm not sure how to know if the exec hook made a difference or not.

**Comment by tylercollier** [comment]
Thanks for that awesome explanation!

I think the reason I haven't had "problems" with this issue in a while is that when I see the "command not found, it exists in these node versions", I just go ahead and install it globally in the version of node that I'm in, which I realize is kind of against the point of npx.

I love nodenv and am extremely grateful for it so I'd be happy to help test the npx.bash script in any way you'd like. I'm guessing though that you're confident of the academic cases and want more "in the wild" tests, so here's what I'll do. I'll put a reminder on my calendar for a month from now and check in then at the latest, but if I encounter a scenario earlier I'll report. I'm currently a coding bootcamp instructor so I am often working with multiple versions of node so I bet I run into something before long :-)

**Comment by tylercollier** [comment]
**I posted this a few minutes ago with a different github account. Reposting it with my original account.**

Update as promised. I tried it just now and it worked. I am on a new machine and I installed nodenv via homebrew. I have node versions 10.15.0 (set as global) and 11.6.0, and I installed create-react-app globally via npm in version 11.6.0. I then ran `nodenv rehash`. When I typed `npx create-react-app blah`, it said (as expected):

```
nodenv: create-react-app: command not found

The `create-react-app' command exists in these Node versions:
  11.6.0
```

I then put the `npx.bash` script where you said. I ran the same CLI line as above, and it worked! It ran create-react-app with node 10.15.0. Great!

I told you I am a bootcamp instructor and hope to report on "in the wild" conditions. I switched companies and my first class with this new company starts tomorrow, so I'll put another reminder on my calendar for a month from now and report back.

**Comment by tylercollier** [comment]
I don't really know why it might be a good idea _not_ to have the exec script included by default. But I'd vote to put it in the new version. That way if I want that behavior on all my machines, I simply update to the newest nodenv (a little easier than manually creating the `npx.bash`).

**Comment by tylercollier** [comment]
I haven't had the opportunity to show many others to use nodenv as I intended. However, I have multiple machines and today used a different machine than previous. I tried to use `npx` and got the error as originally described. I switched my `nodenv` to the `npx` branch and ran the npx command again and it worked perfectly. I'd say LGTM. Thanks for the great work!
