### ISSUE TITLE
Local cache directory

### ISSUE THREAD

**Issue by zxiiro** [nodenv/nodenv#81]
When running `nodeenv -p` it always redownloads the node package. I was wondering if there was a way to cache node locally and pass a parameter so that `nodeenv -p` will downloaded from a local repo instead?

**Comment by jasonkarns** [comment]
I think you have the wrong project. Our cli is `nodenv` (note the single e). And `nodenv -p` wouldn't be a full command. (Would need a subcommand, `install`, or something.

**Comment by zxiiro** [comment]
Woops sorry about that.

**Comment by jasonkarns** [comment]
No problem. And might I suggest perhaps switching to this nodenv? We've merged with wfarr's nodenv, are the sole `nodenv` in homebrew, and regularly pull updates from the upstream rbenv project, from which most nodenv variants were forked. </sales-pitch>

**Comment by zxiiro** [comment]
I'll take a look and see if it fits our needs. Thanks :)
