### ISSUE TITLE
Can not remove shim

### ISSUE THREAD

**Issue by stereobooster** [nodenv/nodenv#82]
Story: I installed ocaml with homebrew, after that installed reason-cli with npm with `-g`, it appears that reason-cli shadows ocaml binaries, so I uninstalled `reason-cli`. But nodenv still keeps shims. I can remove them manually with `rm -rf`, but they reappear again after shell restart. Tried `nodenv rehash`, but without success. How to stop nodenv from creating those shims?

**Comment by jasonkarns** [comment]
> But nvm still keeps shims.

Are you talking about `nvm` or `nodenv`?

If you're sure this is with nodenv and not nvm (which is a different tool), I'd suggest running `nodenv which reason-cli` as that will show you which nodes still have reason-cli installed, thus triggering the shim regeneration.

**Comment by stereobooster** [comment]
> Are you talking about nvm or nodenv?

This is what they call "brand confusion". But It is nodenv.

```
which ocamlc
/opt/boxen/nodenv/shims/ocamlc
nodenv which ocamlc
nodenv: ocamlc: command not found
```

**Comment by jasonkarns** [comment]
@stereobooster If you can, I'd read through this thread: https://github.com/rbenv/rbenv/issues/548 as that explains when and why a shim would remain. Let's see if that resolves it...

**Comment by jasonkarns** [comment]
Specifically, try: `ls "$(nodenv root)"/versions/*/bin/` and see if the bin exists in any of your installed versions.

**Comment by jasonkarns** [comment]
As this question keeps popping up, I've started a FAQ page on the wiki. https://github.com/nodenv/nodenv/wiki/FAQ#cannot-remove-shim

**Comment by jasonkarns** [comment]
Closing as stale

**Comment by Schoonology** [comment]
Stale, and yet still useful. This is, apparently, still the first result when trying to figure this out. 😆
