### ISSUE TITLE
node-0.12.18 missing

### ISSUE THREAD

**Issue by mcandre** [nodenv/nodenv#93]
Could nodenv please add Node.js v0.12.18 to the install list, in order to support some older Node.js projects?

As a workaround, I'm using Node.js v0.12.17, and then refactoring projects to upgrade to v4 for better support. (Lol all these old versions are so far behind, but I'm jumping my projects up the LTS ladder as fast as I can!)

**Comment by jasonkarns** [comment]
0.12.18 has been available since Dec 2016 25293826644c8e460d2acec9698968d9dda9c86b
