### ISSUE TITLE
Node.js v4.8 and v4.7 series missing

### ISSUE THREAD

**Issue by mcandre** [nodenv/nodenv#94]
nodenv is missing several v4 releases:

* [ ] 4.8.6
* [ ] 4.8.3
* [ ] 4.8.2
* [ ] 4.8.1
* [ ] 4.7.3
* [ ] 4.7.0

As a workaround, I'm upgrading my Node.js projects from v0.12.17 (v0.12.18 is missing) up to v4.6.2. And then I'll probably jump up to the v6 series after that.

**Comment by jasonkarns** [comment]
* [ ] 4.8.6 - https://github.com/nodenv/node-build/commit/dc4df589c8d0c64d2a71a6c62230cf738cf5dd65
* [ ] 4.8.3 - https://github.com/nodenv/node-build/commit/6a96c67587f2eff146d3712af6badeee44c6e575
* [ ] 4.8.2 - https://github.com/nodenv/node-build/commit/1f54425d0f6b2eec3e360bbdedea8b27a440a879
* [ ] 4.8.1 - https://github.com/nodenv/node-build/commit/66d8127d074f6d2dcb6a825afdff93e5f6d6f377
* [ ] 4.7.3 - https://github.com/nodenv/node-build/commit/dd382ea076d43f9bba54827d199939dcf55d1ad7
* [ ] 4.7.0 - https://github.com/nodenv/node-build/commit/147852abd9c6c3d5100e9a889ad1b5b6bae1c8d2
