### ISSUE TITLE
v6 series missing latest releases

### ISSUE THREAD

**Issue by mcandre** [nodenv/nodenv#95]
* [ ] 6.12.0
* [ ] 6.11.5
* [ ] 6.11.4
* [ ] 6.11.3
* [ ] 6.11.2
* [ ] 6.11.1
* [ ] 6.11.0
* [ ] 6.10.3
* [ ] 6.10.2
* [ ] 6.10.0
* [ ] 6.9.5
* [ ] 6.9.4
* [ ] 6.9.3
* [ ] 6.9.2

As a workaround, I'm upgrading my Node.js v4 projects to v6.9.1, and then I'll probably skip past the missing v6 updates and jump into the v8 LTS series.

**Comment by jasonkarns** [comment]
All of these are available: https://github.com/nodenv/node-build/tree/master/share/node-build
