### ISSUE TITLE
v8 series missing

### ISSUE THREAD

**Issue by mcandre** [nodenv/nodenv#96]
The nodeenv registry appears to be missing releases from the latest stable Node.js series, v8:

* [ ] 8.9.1
* [ ] 8.9.0
* [ ] 8.8.1
* [ ] 8.8.0
* [ ] 8.7.0
* [ ] 8.6.0
* [ ] 8.5.0
* [ ] 8.4.0
* [ ] 8.3.0
* [ ] 8.2.1
* [ ] 8.2.0
* [ ] 8.1.4
* [ ] 8.1.3
* [ ] 8.1.2
* [ ] 8.1.1
* [ ] 8.1.0
* [ ] 8.0.0

As a workaround, users can either manage Node.js versions with nvm, or stick with the Node.js v6 series for now.

**Comment by jasonkarns** [comment]
All of these have been available within days of their release: https://github.com/nodenv/node-build/tree/master/share/node-build

**Comment by mcandre** [comment]
Curious, why does my nodenv report these as missing?

Do I need to update nodenv itself? I'm using nodenv 1.0.0.

**Comment by jasonkarns** [comment]
https://github.com/nodenv/nodenv/wiki/FAQ#available-node-versions-are-out-of-date

**Comment by jasonkarns** [comment]
I just added that wiki entry to help others that have this question, too

**Comment by mcandre** [comment]
Awesome that is super helpful!
