### ISSUE TITLE
`NODENV_VERISON=system nodenv exec npm` hangs indefinitely

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [nodenv/nodenv#97]
So, I can't seem to track down why this explodes:

```
❯ ~ [41s] npm --version
5.3.0

❯ ~ which npm
/usr/local/opt/nodenv/shims/npm

❯ ~ nodenv shell system

❯ ~ which npm
/usr/local/opt/nodenv/shims/npm

❯ ~ npm --version      
[hangs forever] ^C

❯ ~ [44s] nodenv whence npm  
8
8.6
8.6.0
```

How can I figure out what `npm` this is invoking, or otherwise track down the source of this bug?

**Comment by jasonkarns** [comment]
Sorry @ELLIOTTCABLE did you get this figured out? Still occurring?

**Comment by ELLIOTTCABLE** [comment]
Unfortunately, it's too far back in the distant past; I don't even know which *computer* this was failing on. 😕
